# Generated by Django 5.2.1 on 2025-05-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='نام بازیگر')),
                ('poster', models.URLField(blank=True, null=True, verbose_name='تصویر بازیگر')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ایدی بازیگر')),
                ('popularity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='معروفیت')),
                ('movie_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد فیلم\u200cها')),
            ],
            options={
                'verbose_name': 'بازیگر',
                'verbose_name_plural': 'بازیگران',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='شناسه TMDB کارگردان')),
                ('full_name', models.CharField(max_length=500, unique=True, verbose_name='نام کارگردان')),
                ('poster', models.URLField(blank=True, null=True, verbose_name='تصویر کارگردان')),
                ('popularity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='معروفیت')),
                ('movie_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد فیلم\u200cها')),
            ],
            options={
                'verbose_name': 'کارگردان',
                'verbose_name_plural': 'کارگردان\u200cها',
            },
        ),
    ]
