# Generated by Django 5.2.1 on 2025-05-20 16:22

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebrity', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='عنوان ژانر')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('translated_genre', models.CharField(default='None', max_length=50, verbose_name='ژانر ترجمه شده')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آیپی')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('imdb_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='مدت زمان فیلم به دقیقه', null=True)),
                ('poster', models.URLField(blank=True, max_length=500, null=True)),
                ('trailer', models.URLField(blank=True, null=True, verbose_name='تریلر')),
                ('production_country', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True, verbose_name='شبکه')),
                ('is_dubbed', models.BooleanField(default=False, verbose_name='دوبله شده')),
                ('is_subtitled', models.BooleanField(default=False, verbose_name='زیرنویس شده')),
                ('tmdb_user_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tmdb_popularity', models.PositiveIntegerField(blank=True, null=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='movies_actor', to='celebrity.actor')),
                ('directors', models.ManyToManyField(blank=True, related_name='movies_director', to='celebrity.director')),
                ('genres', models.ManyToManyField(blank=True, to='movielenz.genre')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movielenz.movie')),
                ('number_of_seasons', models.PositiveIntegerField(default=1, verbose_name='تعداد فصل\u200cها')),
                ('episode_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد قسمت\u200cها')),
                ('series_status', models.CharField(blank=True, choices=[('ongoing', 'در حال پخش'), ('ended', 'به پایان رسیده'), ('canceled', 'لغو شده'), ('upcoming', 'به زودی'), ('pilot', 'پایلوت')], default='ongoing', max_length=50, null=True, verbose_name='وضعیت سریال')),
            ],
            options={
                'verbose_name': 'سریال',
                'verbose_name_plural': 'سریال\u200cها',
            },
            bases=('movielenz.movie',),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='movielenz.type', verbose_name='Parent Type')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'type',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movielenz.type', verbose_name='Type'),
        ),
    ]
