# Generated by Django 5.2.1 on 2025-05-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielenz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
