# Generated by Django 5.2.1 on 2025-05-29 19:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('movielenz', '0002_alter_type_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='آدرس ایمیل')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='عکس پروفایل')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('subscription_status', models.CharField(choices=[('free', 'رایگان'), ('premium', 'ویژه'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده')], default='free', max_length=10, verbose_name='وضعیت اشتراک')),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع اشتراک')),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان اشتراک')),
                ('preferred_language', models.CharField(default='fa', help_text="مثال: 'fa' برای فارسی, 'en' برای انگلیسی", max_length=10, verbose_name='زبان ترجیحی')),
                ('groups', models.ManyToManyField(blank=True, help_text='گروه\u200cهایی که این کاربر به آن\u200cها تعلق دارد. یک کاربر تمام مجوزهای اعطا شده به هر یک از گروه\u200cهای خود را دریافت می\u200cکند.', related_name='user_account_user_groups', related_query_name='user', to='auth.group', verbose_name='گروه\u200cها')),
                ('preferred_genres', models.ManyToManyField(blank=True, related_name='users_preferring', to='movielenz.genre', verbose_name='ژانرهای مورد علاقه')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='مجوزهای خاص برای این کاربر.', related_name='user_account_user_permissions', related_query_name='user', to='auth.permission', verbose_name='مجوزهای کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyWatchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه شیء محتوا')),
                ('watched_at', models.DateTimeField(verbose_name='زمان تماشا')),
                ('progress_seconds', models.PositiveIntegerField(blank=True, help_text='میزان تماشای فیلم یا سریال به ثانیه', null=True, verbose_name='پیشرفت (ثانیه)')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_watched_entries', to='user_account.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آیتم اخیراً تماشا شده',
                'verbose_name_plural': 'آیتم\u200cهای اخیراً تماشا شده',
                'ordering': ['-watched_at'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه شیء محتوا')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان افزودن')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آیتم مورد علاقه',
                'verbose_name_plural': 'آیتم\u200cهای مورد علاقه',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه شیء محتوا')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان افزودن')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آیتم لیست تماشا',
                'verbose_name_plural': 'آیتم\u200cهای لیست تماشا',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
